### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/testng/TestNG

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/ExtentReportsExample#2]
I had the `TestNG.xml` file immediately under the project directory. I tried to run the test in IntelliJ IDEA. I right-clicked the TestNG.xml and chose "Run". Then I got the following error.

```
/Users/kazuakiurayama/.sdkman/candidates/java/21.0.1-tem/bin/java -ea -Didea.test.cyclic.buffer.size=1048576 -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=51206:/Applications/IntelliJ IDEA.app/Contents/bin -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath /Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA.app/Contents/plugins/testng/lib/testng-rt.jar:/Users/kazuakiurayama/github/ExtentReportsExample/build/classes/java/test:/Users/kazuakiurayama/github/ExtentReportsExample/build/resources/test com.intellij.rt.testng.RemoteTestNGStarter -usedefaultlisteners false -socket51205 @w@/private/var/folders/7m/lm7d6nx51kj0kbtnsskz6r3m0000gn/T/idea_working_dirs_testng.tmp -temp /private/var/folders/7m/lm7d6nx51kj0kbtnsskz6r3m0000gn/T/idea_testng.tmp
Exception in thread "main" java.lang.NoClassDefFoundError: org/testng/TestNG
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:101)
Caused by: java.lang.ClassNotFoundException: org.testng.TestNG
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 10 more

Process finished with exit code 1

```

It seems that IntelliJ IDEA could not setup a CLASSPATH for the `<projectDir>/TestNG.xml` to run the TestNG tests.

**Comment by kazurayam** [comment]
I tried a thing.
I moved the `TestNG.xml` file into the `src/test` directory.
Then the test ran without the ClassNotFoundException.
